version: '3'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: digitalocean.com/php
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        build:
            context: ./
            dockerfile: docker/nginx.docker
        restart: unless-stopped
        tty: true
        ports:
            - "9000"
            - "80:80"
            - "443:443"
        networks:
            - app-network
        volumes:
            - ./:/var/www

    #MySQL Service
    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
